### ISSUE TITLE
Generic discussions about using metaprogramming with DataFrames

### ISSUE THREAD

**Issue by tshort** [JuliaData/DataFramesMeta.jl#1]
Here are several issues that discuss metaprogramming and/or different
approaches to query and manipulate DataFrames:
- https://github.com/JuliaStats/DataFrames.jl/issues/523
- https://github.com/JuliaStats/DataFrames.jl/pull/472
- https://github.com/JuliaStats/DataFrames.jl/issues/504
- https://github.com/JuliaStats/DataFrames.jl/issues/381
- https://github.com/JuliaStats/DataFrames.jl/issues/369

Please add additional comments here on better approaches to querying DataFrames.

**Comment by davidagold** [comment]
With regards to [DataFrames Issue #369 - Ergonomic ways of recoding data](https://github.com/JuliaStats/DataFrames.jl/issues/369), I have been working on a simple `@byrow` macro that supports `if` blocks:

```
julia> df
8x3 DataFrame
| Row | a | b   | col_1    |
|-----|---|-----|----------|
| 1   | 1 | "M" | 0.731688 |
| 2   | 2 | "F" | 0.294839 |
| 3   | 3 | "M" | 0.667601 |
| 4   | 4 | "M" | 0.24186  |
| 5   | 5 | "F" | 0.247961 |
| 6   | 6 | "F" | 0.302071 |
| 7   | 7 | "M" | 0.167708 |
| 8   | 8 | "F" | 0.664298 |

julia> @byrow df if :a > 1; :b = "foo" end

julia> df
8x3 DataFrame
| Row | a | b     | col_1    |
|-----|---|-------|----------|
| 1   | 1 | "M"   | 0.731688 |
| 2   | 2 | "foo" | 0.294839 |
| 3   | 3 | "foo" | 0.667601 |
| 4   | 4 | "foo" | 0.24186  |
| 5   | 5 | "foo" | 0.247961 |
| 6   | 6 | "foo" | 0.302071 |
| 7   | 7 | "foo" | 0.167708 |
| 8   | 8 | "foo" | 0.664298 |

julia> macroexpand(:( @byrow df if :a > 1; :a = 3x end ))
:(for #1619#row = 1:length(df[1])
        if df[#1619#row,:a] > 1 # line 1:
            df[#1619#row,:a] = 3x
        end
    end)
```
You can also use `begin` `end` blocks to improve readability:
```
julia> @byrow df begin
                   if :a > 1
                       :b = "bar"
                   end
                 end

julia> df
8x3 DataFrame
| Row | a | b     | col_1    |
|-----|---|-------|----------|
| 1   | 1 | "M"   | 0.731688 |
| 2   | 2 | "bar" | 0.294839 |
| 3   | 3 | "bar" | 0.667601 |
| 4   | 4 | "bar" | 0.24186  |
| 5   | 5 | "bar" | 0.247961 |
| 6   | 6 | "bar" | 0.302071 |
| 7   | 7 | "bar" | 0.167708 |
| 8   | 8 | "bar" | 0.664298 |
```
I haven't tested performance yet. My approach is very simple and doesn't generate a new function for which type inference is unimpeded, as in @tshort 's implementation of `@with`. Furthermore, I haven't yet experimented with the Devectorize.jl package, and I don't know how much this macro overlaps with that. All that being said, I think this syntax could go a long ways towards ameliorating issues such as described in 369 and in [this thread](https://groups.google.com/forum/?hl=en#!topic/julia-users/ivjiBS49D8E).

I'm very happy to continue working on this functionality for DataFramesMeta if folks here like it. Immediate next steps are to add more expressive power, such as the ability to index into an array `x[:]` that isn't columns of the implicit dataframe. This probably will require some approach to denote that the index for `x[:]` needs to be hooked into the loop generated by the macro, e.g.:
```julia
 @byrow df begin
            if :a > ^x
                :a = 2(^x)
            end
        end
```
to get
```julia
for row in 1:length(df[1])
    if df[row, :a] > x[row]
        df[row, :a] = 2x[row]
    end
end
```
If anybody has thoughts, please do share them!

**Comment by nalimilan** [comment]
@davidagold Interesting. Indeed it looks like what I was describing in JuliaStats/DataFrames.jl#369 I don't think you need to worry about Devec.jl, I see it as orthogonal to this kind of macro.

**Comment by tshort** [comment]
I like this idea, @davidagold--it would make a good addition to DataFramesMeta. I don't think it will perform well with the indexing inside the loop. For better performance, you could try to convert to something like the following:

```julia
@with df for row in 1:length(df[1])
    if :a[row] > x[row]
        :a[row] = 2x[row]
    end
end
```

**Comment by davidagold** [comment]
Thank you both for your inputs! Tom, you're right about performance:
```julia
using DataArrays, DataFrames, DataFramesMeta

srand(1)
n = 10_000_000
a = rand(n)
b = rand(n)
c = rand(n)
d = zeros(n)
df = DataFrame(a=a, b=b, c=c, d=d)

function f1()
    x = 0.0
    @byrow df (begin
        if :a < :b
            x += :b * :c
        end
    end)
    return x
end

function f2()
    x = 0.0
    a = convert(Array, df[:a])
    b = convert(Array, df[:b])
    c = convert(Array, df[:c])
    for row in 1:10_000_000
        if a[row] < b[row]
            x += b[row] * c[row]
        end
    end
    return x
end

function f3()
    x = 0.0
    @with df (begin
        for row in 1:length(df[1])
            if :a[row] < :b[row]
                x += :b[row] * :c[row]
            end
        end
    end)
    return x
end

function g1()
    @byrow df begin
        if :a < :b
            :d = :b * :c
        end
    end
end

function g2()
    a = convert(Array, df[:a])
    b = convert(Array, df[:b])
    c = convert(Array, df[:c])
    for row in 1:10_000_000
        if a[row] < b[row]
            df[row, :d] = b[row] * c[row]
        end
    end
end

function g3()
    @with df begin
        for row in 1:length(df[1])
            if :a[row] < :b[row]
                :d[row] = :b[row] * :c[row]
            end
        end
    end
end

f1()
f2()
f3()
g1()
g2()
g3()

println("f1: ", @time(f1()))
println("f2: ", @time(f2()))
println("f3: ", @time(f3()))
println("g1: ", @time(g1()))
println("g2: ", @time(g2()))
println("g3: ", @time(g3()))
```
gives
```
elapsed time: 5.64861955 seconds (1760130256 bytes allocated, 20.85% gc time)
f1: 1.6670060387376607e6

elapsed time: 2.464278376 seconds (1120132752 bytes allocated, 37.23% gc time)
f2: 1.6670060387376607e6

elapsed time: 3.435715078 seconds (1280088960 bytes allocated, 23.48% gc time)
f3: 1.6670060387376607e6

elapsed time: 6.304825319 seconds (1920164824 bytes allocated, 20.65% gc time)
g1: nothing

elapsed time: 3.157730953 seconds (1360203344 bytes allocated, 31.98% gc time)
g2: nothing

elapsed time: 3.384456055 seconds (1200062760 bytes allocated, 23.14% gc time)
g3: nothing
```

I'll go work on your suggestion. May I submit it as a PR when it's ready?

**Comment by davidagold** [comment]
@tshort After implementing your suggestion the same tests as above now give:
```
elapsed time: 3.841014122 seconds (1280088960 bytes allocated, 25.72% gc time)
f1: 1.6670060387376607e6

elapsed time: 2.611359312 seconds (1120132752 bytes allocated, 37.45% gc time)
f2: 1.6670060387376607e6


elapsed time: 3.53787387 seconds (1200062760 bytes allocated, 22.51% gc time)
g1: nothing

elapsed time: 3.085036564 seconds (1360203344 bytes allocated, 32.94% gc time)
g2: nothing
```
where (as a reminder) f1/g1 use `@byrow` (which now essentially does the same thing as f3/g3 above) and f2/g2 converts DataFrame columns to Arrays and loops through the latter. If you have any more suggestions for performance, I am game to investigate.

**Comment by davidagold** [comment]
Aaactually, I've run into an issue. Going to file.

**Comment by tshort** [comment]
Yes to the PR when ready, @davidagold. As far as your tests, try them out without using globals. They should all be faster.
