### ISSUE TITLE
[bug] @transform not playing well with groupby

### ISSUE THREAD

**Issue by Nosferican** [JuliaData/DataFramesMeta.jl#115]
```
data = DataFrame(Subject = categorical(repeat(1:24, inner = 2)),
                 Sequence = categorical(repeat(1:4, inner = 12)),
                 Period = categorical(repeat(1:2, 24)),
                 AUC = rand(48)) |>
       groupby(:Subject) |>
       (df -> @transform(df, δ = [missing, first(diff(:AUC))]))
```

**Comment by pdeffebach** [comment]
The code that does this weird thing is [here](https://github.com/JuliaData/DataFrames.jl/blob/5824b6ba02809f6ab4ba1453dfa3bd8e9adfd259/src/deprecated.jl#L1327). In pre-DataFramesMeta days it looks like we overloaded the `|>` operator to have some unintuitive behavior. 

The solution is just to delete those deprecations. That particular deprecation happened 11 months ago so it's probably been enough time.

**Comment by Nosferican** [comment]
Closing this issue in favor of #116.
