### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by matthieugomez** [JuliaData/DataFramesMeta.jl#118]
I think that `DataFramesMacros` would be a better name for this package. I am not a native speaker nor a computer scientist but `DataFramesMeta` sounds to me like something that unifies multiple implementation of dataframes, i.e. what `Tables.jl` does.

**Comment by nalimilan** [comment]
Yes, the name isn't very explicit. OTOH renaming is also confusing for users...

**Comment by tshort** [comment]
I also dislike the name, but it has been around for a bit.

**Comment by ararslan** [comment]
Since 4 Feb 2014, to be exact
