### ISSUE TITLE
`@linq` anonymous function piping doesn't work like normal

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFramesMeta.jl#120]
I thought there was an issue somewhere else for this but I couldn't find it. 

```
julia> using DataFrames, DataFramesMeta
julia> df = DataFrame(a = rand(1:2, 10), b = randn(10))
julia> t = @ling df |>
       transform(c = 1) |>
       (d -> d[:t] = 4)
#7 (generic function with 1 method)
```

It's returning an anonymous function. However the following works: 

```
julia> using DataFrames, DataFramesMeta
julia> df = DataFrame(a = rand(1:2, 10), b = randn(10))
julia> t = @ling df |>
       transform(c = 1) |>
       (d -> d[:t] = 4)() # extra parentheses
4
```

I think it has to do with the following line: https://github.com/JuliaData/DataFramesMeta.jl/blob/db41eed353ba3fed848aa482de1629678bf8355f/src/linqmacro.jl#L91, where the anonymous function doesn't have a `:call` anywhere. 

Normal piping would have this work fine. 

```
julia> df |> (d -> d[:t] = 4)
```

cc @bkamins since I'm not sure how to fix this.

**Comment by bkamins** [comment]
Well a fix is:
```
    if e.head == :call && e.args[1] == :|> && isa(e.args[3], Expr) && e.args[3].head == :call
```
because you have to make sure that you run `insert!(newe.args, 2, e.args[2])` to `df` to `e.args[3]` only if it is already function call (if it is not a function call `|>` will transform it to a single argument function call later in the process).

Note however that your example:
```
julia> t = @linq df |>
       transform(c = 1) |>
       (d -> d[:t] = 4)
```
is not very useful (maybe on purpose) as `d -> d[:t] = 4` mutates the result of `transform(c = 1)` which is not captured later. You probably wanted:

```
julia> t = @linq df |>
       transform(c = 1) |>
       (d -> (d[:t] = 4; d))
10×4 DataFrame
│ Row │ a     │ b          │ c     │ t     │
│     │ Int64 │ Float64    │ Int64 │ Int64 │
├─────┼───────┼────────────┼───────┼───────┤
│ 1   │ 2     │ -0.54309   │ 1     │ 4     │
│ 2   │ 1     │ 1.41007    │ 1     │ 4     │
│ 3   │ 2     │ -0.436344  │ 1     │ 4     │
│ 4   │ 2     │ -0.481977  │ 1     │ 4     │
│ 5   │ 1     │ 0.0847813  │ 1     │ 4     │
│ 6   │ 1     │ -0.323766  │ 1     │ 4     │
│ 7   │ 2     │ -0.0417934 │ 1     │ 4     │
│ 8   │ 2     │ -0.975263  │ 1     │ 4     │
│ 9   │ 2     │ 1.03838    │ 1     │ 4     │
│ 10  │ 1     │ 0.373917   │ 1     │ 4     │
```

right?

**Comment by pdeffebach** [comment]
yes that is definitely correct. I can try to get a PR together for this soon.

**Comment by pdeffebach** [comment]
Closed as `@linq` is deprecated in favor of Chain.jl
