### ISSUE TITLE
Drop Columns using Select

### ISSUE THREAD

**Issue by versipellis** [JuliaData/DataFramesMeta.jl#124]
In R's dplyr, you could drop a column using `select(df,-columnName)` as part of pipe chaining. This is particularly handy for datasets where you have a large number of columns, and only want to drop one column without retyping the rest of the column names. It'd be lovely to see this work with DataFramesMeta's `select` instead of having to break a LINQ chain to use `delete!`

**Comment by nalimilan** [comment]
We should use [InvertedIndices](https://github.com/mbauman/InvertedIndices.jl)'s `Not` for this.

**Comment by pdeffebach** [comment]
This should be pretty easy to implement, see the way we escape function arguments with `cols`

https://github.com/JuliaData/DataFramesMeta.jl/blob/86263849b7fa252838f9149c0c4c2e1493a085b2/src/DataFramesMeta.jl#L37

**Comment by pdeffebach** [comment]
Closed as a duplicate of #283
