### ISSUE TITLE
Rename `^` to `syms`

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFramesMeta.jl#125]
`^()`  is currently used to refer to a symbol on its own. for example, 

`df @> transform(x = :b)` will make a new column `:x` which looks like the column `:b`, while

`df @> transform(x = ^(:b))` makes a new column `:x` and fills it with the symbol `:b`. There is nothing about `^()` that indicates this behavior. I propose renaming it to `syms`, because it escapes `Symbol`s and has the same number of letters as `cols`.

**Comment by nalimilan** [comment]
Doesn't JuliaDBMeta use `cols` for this? Cc: @piever

**Comment by piever** [comment]
`cols` is used to recognize things that evaluate to a symbol, say::

```julia
a = :SepalLength
@with iris cols(a)
```

Whereas `^` is to escape something to be used as a symbol, for example `@map iris ^(:a)` will return a column full of the symbol `:a`.

I disagree with the renaming. `^` can escape a whole expression and not only a symbol (it basically takes it out of the macro and evaluates it as is, so the name `syms` is not completely correct. If anything, for consistency I'd be in favor of adding a infix operator version of `cols`, say `@with iris $a`, which is in some sense interpolation, in that `a` is evaluated before replacing symbols with columns.

**Comment by nalimilan** [comment]
Got it. Yes, `$` for cols kind of makes sense. Maybe we could use `esc` for `^`?

(I still kind of wish we treated all names as columns by default, so that we wouldn't need to escape symbols...)

**Comment by pdeffebach** [comment]
> Got it. Yes, `$` for cols kind of makes sense. Maybe we could use `esc` for `^`?

This is okay, but `cols` also "escapes" the input by evaluating what's inside. 

```
a = :x 
@transform(df, newcol = cols(a)
```
 which is the same as 

```
@transform(df, newcol = :x) # the column `:x` in df. 
```

Basically we have two divergent ways to escape the variable `a`. 

> (I still kind of wish we treated all names as columns by default, so that we wouldn't need to escape symbols...)

Don't we do this already? Or do you mean full tidy evaluation?

**Comment by nalimilan** [comment]
So what's the conclusion here?

**Comment by pdeffebach** [comment]
It's weird that we have `cols` instead of `col`... But we should rename this to `syms` for consistency.

**Comment by pdeffebach** [comment]
Closing this, `^()` is fine, and now that we use `$` intead of `cols` it doesn't make sense to have `syms`.
