### ISSUE TITLE
Add begin block form for @linq

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaData/DataFramesMeta.jl#136]
It would be nice if the `@linq` macro natively supported using a begin block. The related example in the docs requires using the `@>` macro from Lazy.jl, and thus requires introducing Lazy.jl as a dependency of one's package.

What I have in mind is syntax like the following:

```julia
@linq df begin
    @transform(y = 10 * :x)
    @where(:a .> 2)
    @by(:b, meanX = mean(:x), meanY = mean(:y))
    @orderby(:meanX)
    @select(:meanX, :meanY, var = :b)
end
```

**Comment by pdeffebach** [comment]
Closed in favor of #177
