### ISSUE TITLE
Groupby is not working

### ISSUE THREAD

**Issue by hajsf** [JuliaData/DataFramesMeta.jl#139]
I've the below code:
```julia
using DataFramesMeta, DataFrames

df = DataFrame(name=["Kirk", "Sally", "Kirk"], age=[60., 42., 59.], children=[3,5,2])

x = @from i in df begin
    @where i.age>50
    @select {i.name}
    @groupby(i.name)
    @collect DataFrame
end

println(x)
```
The output is:
```bash
2x1 query result
name
────
Kirk
Kirk
```

While I expect it to do gouping and give one output only?

**Comment by bkamins** [comment]
@hajsf - you have again opened an issue that does not belong to DataFramesMeta.jl. Please consider submitting the issues to relevant Queryverse packages if you think you found a bug.

If I understand your code correctly in DataFramesMeta.jl you would write it:
```
julia> @linq df |>
       where(:age .> 50) |>
       select(:name) |>
       groupby(:name) |>
       DataFrame
2×1 DataFrame
│ Row │ name   │
│     │ String │
├─────┼────────┤
│ 1   │ Kirk   │
│ 2   │ Kirk   │
```
to get exactly what you have reported.
