### ISSUE TITLE
Why does `@byrows!` contain the bang (!) at the end of its name when it is not modifying the input argument?

### ISSUE THREAD

**Issue by hurak** [JuliaData/DataFramesMeta.jl#140]
Why does `@byrows!` contain the bang (!) at the end of its name when it is not modifying the input argument?

## An example

First, define some DataFrame `df`

```julia 
julia> df = DataFrame(x = 1:3, y = [2, 1, 2])
3×2 DataFrame
│ Row │ x     │ y     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 2     │
│ 2   │ 2     │ 1     │
│ 3   │ 3     │ 2     │
```
Now do some modifications using `@byrows!`

 ```julia
@byrow! df if :x > :y; :x = :y *3 end
3×2 DataFrame
│ Row │ x     │ y     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 2     │
│ 2   │ 3     │ 1     │
│ 3   │ 6     │ 2     │
```
and yet the original DataFrame `df` remains intact:

```julia
julia> df
3×2 DataFrame
│ Row │ x     │ y     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 2     │
│ 2   │ 2     │ 1     │
│ 3   │ 3     │ 2     │
```

**Comment by henriquebecker91** [comment]
Great question, I stumbled in this behavior again today. I think it is a bug, because the documentation uses as the first example of `@byrow!`:

> `@byrow! df if :A > :B; :A = :B * :C end`

That makes no sense without the input argument mutation. Then, in the sequence, in the context of the special syntax for new columns, the documentation says:

> Note that the returned `AbstractDataFrame` includes these new columns, but the original `df` is not affected.

As this was an exception of the behavior just for the case in which new columns are added.

**Comment by pdeffebach** [comment]
I think this is a bug as well, @bkamins do you agree?. 

@henriquebecker91  or @hurak Would either mind opening a PR to deprecate this behavior?

That is, people will still be able to use `@byrow!` but they will get a warning and be told to use `@byrow` instead.

**Comment by henriquebecker91** [comment]
Done: https://github.com/JuliaData/DataFramesMeta.jl/pull/154

**Comment by bkamins** [comment]
Yes - `@byrow`  is better I think.
