### ISSUE TITLE
Recommending Lazy.jl is problematic

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/DataFramesMeta.jl#159]
Because Lazy.jl exports `groupby` which clashes with DataFrames.jl!

So it seems like we need a `@groupby` macro to disambiguate.

**Comment by pdeffebach** [comment]
I think the solution here would be to only recommend the piping operators `@>` etc. from Lazy and have the docs say `using Lazy: @>` or something. 

A `@groupby` macro might be useful, but it depends on how we ultimately decide to escape `Symbol`s. If we go with `@groupby(df, x)` where `x` is a literal, then a macro makes sense. If not, no need for a macro.

**Comment by bkamins** [comment]
If we want to keep recommending Lazy.jl I think what @pdeffebach suggests is a way to go - would you care to make a PR to the docs?

**Comment by xiaodaigh** [comment]
> `@groupby` macro might be useful

A macro is insurance policy. If the repo continues to recommend Lazy.jl then its conceivable that a user would just `using Lazy` and wonder why `groupby` is throwing an error? We can recommend to use `using Lazy: @>` but that's relying on users and to follow and not to forget.

If we have a `@groupby` then even if the user did `using Lazy` then he or she can always use `@groupby` and avoid running into issues.

**Comment by xiaodaigh** [comment]
See #161
