### ISSUE TITLE
@byrow not defined

### ISSUE THREAD

**Issue by VitaminBrad** [JuliaData/DataFramesMeta.jl#160]
I'm sure this is likely simply something very stupid on my end, but is there any idea why this is happening?

Thanks!

![](https://i.imgur.com/4gpUnHq.png)

**Comment by pdeffebach** [comment]
We haven't ahd a release since fixing `@byrow`. `0.5.1`. You want `@byrow!` which has the same behavior, but different (incorrect) name which was fixed in #154

**Comment by VitaminBrad** [comment]
Ok, thanks!
