### ISSUE TITLE
Technical clean-up after #163

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFramesMeta.jl#169]
This issue serves as a tracker after #163 is merged. On the To-do list are

* Understand `@linq` and why we need to support `:kw` type expressions in `fun_to_vec`

I will create other issues for new features that are *not* internal after #163 is merged.

**Comment by pdeffebach** [comment]
The reason we need a `:kw` is because 

1. When `@transform` sees something like `y = :x .+ :b`, it has no knowledge that `y = ...` will be eventually used in a function call. 
2. When julia parses `transform(df, y = :x .+ :b)`, which it does in `@linq`, Julia knows that `y = :x .+ :b` happens inside a function call (even though it doesn't actually execute `:x .+ :b`!), and thus makes the head of the expression `:kw` instead of `(=)`. 

Fortunately, this kind of parsing doesn't affect anything if we decide to allow `@transform(df, :y = :x .+:b)`

**Comment by bkamins** [comment]
>  this kind of parsing doesn't affect anything if we decide to allow `@transform(df, :y = :x .+:b)`

Nice. As said earlier - I think the crucial decision is if we want `x` or `:x` as a reference to the column. In particular `y = :x` is somewhat inconsistent.

**Comment by pdeffebach** [comment]
Yes either way we will have the LHS be the same as the RHS. It's good to know its possible, especially because at least for now `@linq` is a bit of a black box.

**Comment by bkamins** [comment]
Ah - and just to clarify, in which scenario (if in any) the form `col(x) = ...` would be possible (I guess more likely in the one with `:x = :y`) - right?

Also - given the current discussions in DataFrames.jl about returning multiple columns is there some design (except for allowing `=>` form) to handle them?

**Comment by pdeffebach** [comment]
`cols(x)` would be possible definitely. I would want it in there no matter what outcome `:x` vs `x` we landed on. The fact that this is so unintuitive to do in `dplyr` drives me crazy!

Given that the user gets to think of DataFramesMeta as a tool for constructing `source => fun => dest` expressions, I would imagine that any valid multi-column `dest` should be allowed in DataFramesMeta.

**Comment by bkamins** [comment]
That would be great!

**Comment by pdeffebach** [comment]
It looks like I allow for `@select(gd::GroupedDataFrame, args...)` which was new behavior and this is not tested. 

I think we should probably break the ordering of the output in `@transform` when make a new release because it's not worth introducing new behavior in `@select` that is about to be changed and it's also not worth introducing behavior in `@select` that is inconsistent with `@transform`.

**Comment by bkamins** [comment]
I am not as deeply into these things as you now. Can you please write an example what you think should be allowed and what should be disallowed?

**Comment by pdeffebach** [comment]
On current release

* `@transform(gd::GroupedDataFrame, args...)`: allowed, order of rows inconsistent with `DataFrames.transform(gd, args...)`
* `@select(gd::GroupedDataFrame, args...)`: not allowed

On `master`:
* `@transform(gd::GroupedDataFrame, args...)`: allowed, order of rows inconsistent with `DataFrames.transform(gd, args...)`
* `@select(gd::GroupedDataFrame, args...)`: allowed, order of rows *consistent* with `select(gd, args...)`

Long run goals:
*  `@transform(gd::GroupedDataFrame, args...)`: allowed, order of rows *consistent* with `transform(gd, args...)`
*  `@select(gd::GroupedDataFrame, args...)`: allowed, order of rows *consistent* with `select(gd, args...)`

Short run goals: 
* Make both macros work with grouped data frames, add `news.md` entry about change, write tests.

**Comment by bkamins** [comment]
My understanding is that keeping order of rows as in `transform` in DataFrames.jl is important. Actually this was one of the main redesign goals in DataFrames.jl to ensure it.

**Comment by pdeffebach** [comment]
cool, then I will make a PR soon that fixes these tests. What should I do about #178 ? Its motivated by a bug that will be fixed when we change the order of rows after `@transform`. Is it okay to have a bug fix and a breaking change at the same time? Or should I fix the bug with a small PR and *then* make a larger change that requires updating tests.

**Comment by bkamins** [comment]
> Or should I fix the bug with a small PR and then make a larger change that requires updating tests.

It does not matter. We will not make a release until both are done and you are the only contributor, so please choose the approach that is simplest for you.

**Comment by pdeffebach** [comment]
I think everything here has been fixed.
