### ISSUE TITLE
Using strings in `cols`

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFramesMeta.jl#181]
We are missing tests for the following, which errors

```
@transform(df, z = cols("x") + :y)
```

DataFrames throws an error because we end up with 

```
["x", :y] => _f => :z 
```

which mixes a symbol and string in the input vector. 

i don't think think we should disallow using strings inside `cols`. We should probably turn everything into `Symbol`s  like 

```
Symbol.(["x", :y]) => _f = :z 
```

This means we will deviate from DataFrames, but this is an acceptable deviation imo.

**Comment by bkamins** [comment]
I think it is OK, as `cols` signals a column name. But I would convert what is passed in `cols` to a `Symbol` - this would be consistent (so essentially `cols` would work similarly to a `Symbol` function).

In DataFrames.jl I would prefer to disallow mixing strings and `Symbol`s.

**Comment by pdeffebach** [comment]
sounds good. w.r.t DataFrames, would forcing the input to be `Any[]` reduce compilation times though?
