### ISSUE TITLE
Rename `@byrow` to `eachrow`

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFramesMeta.jl#194]
Given that DataFrames has `ByRow`, the macro `@byrow` is confusing. it also potentially conflicts with adding a macro to use `ByRow` in `@transform`. 

`@byrow` is really approximated as 

```
for row in eachrow(df)
....
end
```

therefore it should be renamed to `@eachrow`.

**Comment by bkamins** [comment]
OK

**Comment by pdeffebach** [comment]
Closed via #197
