### ISSUE TITLE
Add the `@rename` macro

### ISSUE THREAD

**Issue by metanoid** [JuliaData/DataFramesMeta.jl#204]
It's not strictly necessary, because `DataFrames.rename` exists, but it is nice to have the keyword argument form.

**Comment by pdeffebach** [comment]
Thanks! 

This will be good to add pre 1.0.

**Comment by pdeffebach** [comment]
Bumping this. Current struggling to rename something programmatically in `dplyr`. Would be great to have this in DataFramesMeta.jl

**Comment by MatthewRGonzalez** [comment]
@pdeffebach would something silly like this be acceptable?

```
macro testrename(x, args...)
    esc(testrename_helper(x, (args...)))
end

function testrename_helper(x, args...)
    t = (args)[1]
    quote
        $DataFrames.rename($x, $t)
    end
end

df = DataFrame(x=rand(10), y=rand(10))

@testrename df [:x, :y] .=> [:g, :q]
@testrename df :x => :k

```

**Comment by MatthewRGonzalez** [comment]
Hi, @pdeffebach. I want to bump this to discuss the design. Should the final version of `@rename` be something like

```
df(old_col1 = 1:10, old_col2 = 1:10)

@rename(df :new_col = :old_col)

@rename df begin  
     :new_col1 = :old_col1
     :new_col2 = :old_col2
end
```
Please let me know what you think!

**Comment by pdeffebach** [comment]
Yes. I guess `rename` should allow arbitrary expressions in the RHS so that you can do 

```
@rename df :newcol = begin
    "old_col" * "1"
end
```

and of course `@rename df $(:x => :y)

**Comment by pdeffebach** [comment]
No. see the `:newcol = ...` at the top, it would be equivalent to 

```
rename(df, ("old_col" * "1") => :new_col)
```

`@rename` should only ever create a `rename(df, a => b, c => d)` type-of expression. No need to bother with the function stuff.

**Comment by MatthewRGonzalez** [comment]
Got it, thanks. I currently have the following:

```
@rename df :new1 = begin 
    $("old_col" * "1")
end
```

however, arbitrary RHS expressions need to be escaped.  Further, arbitrary RHS expressions can not be mixed with other standard expressions. For example

```
@rename(df, :new1 = $("old_col" * "1"), :new2 = :old_col2)
```
errors in the same manner as

```
rename(df, ("old_col" * "1") => :new1, :old_col2 => :new2)
ERROR: MethodError: no method matching rename!(::DataFrame, ::Vector{Pair{A, Symbol} where A})
```

Which I think makes sense if this implementation is to rely on `rename`. Is this sufficient?

**Comment by pdeffebach** [comment]
The error above is because all the old names need to be the same type and all the new names need to be the same type. Just cast everything to `string` in the final expression. i.e., produce

```
rename(df, string(("old_col" * "1")) => string(:new1), string(:old_col2) => string(:new2))
```
