### ISSUE TITLE
Avoid anonymizing single function calls

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaData/DataFramesMeta.jl#207]
Currently, this expression

```julia
@macroexpand @transform(df, b = sum(:a))
```

returns (without linenumbernodes)

```
quote
    (DataFrames).transform(df, begin
            DataFramesMeta.make_source_concrete([:a]) => (begin
                        (var"##311",)->begin
                                sum(var"##311")
                            end
                    end => :b)
        end)
end
```

If the expression `sum(:a)` is analyzed, it is clear that there is only a single function call in there. Therefore, it could be avoided to construct `x -> sum(x)`, which could incur additional compilation cost. Instead, `sum` could be passed directly as in `:a => sum => :b`

**Comment by pdeffebach** [comment]
Yup! Would love a PR for this. It would really help with latency.

**Comment by jkrumbiegel** [comment]
I had a glance at the code, but would you mind pointing me to where you'd insert code like this?

**Comment by pdeffebach** [comment]
https://github.com/JuliaData/DataFramesMeta.jl/blob/c76f1566612867a9c5c5745f38c9530e461a4633/src/DataFramesMeta.jl#L114

you would probably have to add more `if`s to avoid calling `replace_syms!`, and the line 

```
        fun = quote
            $inputargs -> begin
                $body
            end
        end
```

would also have to be changed so it was just `body.args[2]`

**Comment by pdeffebach** [comment]
@jkrumbiegel any updates on tests? I can take over this PR if you are busy.

**Comment by jkrumbiegel** [comment]
oh yeah that would be great if you have time, I'm supposed to be doing other things :)

**Comment by pdeffebach** [comment]
closed via #221

**Comment by jkrumbiegel** [comment]
thanks for bringing this over the finish line! when do you think this and `@byrow` are going to be available in a tagged version, now that dataframes is going to 1.0?

**Comment by pdeffebach** [comment]
I'm going to start `@byrow` tonight. I don't anticipate too many edge cases. 

I won't make a release until 1.0, but will make one right after 1.0. So I guess we are looking at a timeline of about 2 weeks.

**Comment by jkrumbiegel** [comment]
Nice! Anything special about subset? I saw you mention in the other thread that it will take a bit longer. That's just the last piece of the puzzle I guess :)

**Comment by pdeffebach** [comment]
oh yeah. We have to add `subset` and then make `@where` a wrapper for `subset(df, ..., skipmissing=true)`. 

I *don't* want `@subset` and `subset` to have different stories about `missing`, so we need to think about convenient syntax for `coalesce(missing, false)` inside `@subset`.

**Comment by jkrumbiegel** [comment]
`@where` is going to be an alias for `@subset` then?

**Comment by pdeffebach** [comment]
`@where` will be deprecated in favor of `@subset`. But the two will have different stories regarding `missing`. `@subset` will fail on `missing` (because `subset` does) but `@where` will treat `missing`s as `false`. 

We need to add keyword arguments very soon as well in order to allow `@subset(df, ...; skipmissing=true)`.
