### ISSUE TITLE
@eachrow is not found

### ISSUE THREAD

**Issue by tp2750** [JuliaData/DataFramesMeta.jl#209]
Running the first `@eachrow` example in the documentation fails:

```
julia> using DataFrames, DataFramesMeta
[ Info: Precompiling DataFrames [a93c6f00-e57d-5684-b7b6-d8193f3e46c0]
[ Info: Precompiling DataFramesMeta [1313f7d8-7da2-5740-9ea0-a2ca25f37964]

julia> df = DataFrame(A = 1:3, B = [2, 1, 2])
3×2 DataFrame
│ Row │ A     │ B     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 2     │
│ 2   │ 2     │ 1     │
│ 3   │ 3     │ 2     │

julia> df2 = @eachrow df begin 
           :A = :B + 1
       end
ERROR: LoadError: UndefVarError: @eachrow not defined
in expression starting at REPL[3]:1
```

```
julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, sandybridge)
Environment:
  JULIA_DEPOT_PATH = .

(tmp) pkg> st
Status `/tmp/Project.toml`
  [a93c6f00] DataFrames v0.21.8
  [1313f7d8] DataFramesMeta v0.5.1
```

**Comment by pdeffebach** [comment]
yes, we are in the process of putting "real" documentation up so that there are no inconsistencies between documentation on the readme and documentation hosted online. 

can you clarify what you mean by "Documentation". The migration to hosted docs via documenter has not been successful and the readme doesn't give that particular example.

**Comment by tp2750** [comment]
I'm looking at this file: https://github.com/JuliaData/DataFramesMeta.jl/blob/master/docs/src/index.md

Which looks like the old README.

Is @eachrow being deprecated?

**Comment by pdeffebach** [comment]
Thank you!

What's going on is that you are browsing the source code in `master` but you are working with the most recently tagged release on your computer. 

`@eachrow` is not being deprecated. Actually, the opposite. The current syntax, `@byrow!` is being deprecated. You should use `@byrow!`. Note that `@byrow!` does not modify the inputted data frame, despite having an exclamation mark, which is one of the reason it's being deprecated. 

We are actually very very close to making a new release with proper, hosted, documentation, so this disorganized state won't last for long.

**Comment by tp2750** [comment]
Thanks for the clarification!

I'll close and look forward to @eachrow :smile: 

Thanks again for a great package. 
Coming from R the DataFRamesMeta syntax is very familiar.
