### ISSUE TITLE
Add slice macro

### ISSUE THREAD

**Issue by mwip** [JuliaData/DataFramesMeta.jl#214]
Having worked with R in the past, I like to use `slice` for creating subsets of a DataFrame. Would it be possible to add a macro somewhat along the lines of:

```
function slice(x::DataFrame, rows::AbstractVector{UInt64})::DataFrame
    return x[rows, :]
end
-----------------------
julia> df = DataFrame(x = [1,2,3,4], y = [10, 20, 30, 40]);

julia> slice(df, 1)
DataFrameRow
 Row │ x      y     
     │ Int64  Int64 
─────┼──────────────
   1 │     1     10

```

**Comment by bkamins** [comment]
But this is essentially as you say:
```
slice(df, idx) = df[idx, :]
```
what is the benefit of introducing `slice` a a new name in the ecosystem?

**Comment by mwip** [comment]
One would be able to use it in a pipe like 
```
@linq df |>
    slice(1:2)
    # [1:2, :] # does not work
    # _[1:2, :] # also does not work
```

Yet, that could be already available or I am just missing something.

**Comment by bkamins** [comment]
Ah - in DataFramesMeta.jl maybe indeed it is a problem. In DataFrames.jl the following works:
```
@pipe df |>
   _[1:2, :]
```
in DataFramesMeta.jl you need to write:
```
@linq df |>
    getindex(1:2, :)
```

**Comment by mwip** [comment]
Well, that works just fine. Thanks.

**Comment by bkamins** [comment]
Actually this pattern is especially nice as you can replace `getindex` with `view` if you want a view (which is often the case for large data frames).
