### ISSUE TITLE
Unexpected output from @combine when used in Lazy:@>

### ISSUE THREAD

**Issue by dbuffoni** [JuliaData/DataFramesMeta.jl#217]
Hi,
Apparently @combine seems to provide an unexpected result when used in a @> pipe after a transform. 

Please review the following test:

`using DataFrames, DataFramesMeta
using Lazy: @>

df = DataFrame(a = [1, 1, 2, 2], b = [1, 3, 8, 10])
@> begin
    groupby(df, :a)
    #@transform(c = :b.+1)
    @combine(m=sum(:b))
end`

which correctly returns

`2×2 DataFrame
│ Row │ a     │ m     │
│ 1   │ 1     │ 4     │
│ 2   │ 2     │ 18    │`

while uncommenting the @transform the groups are lost and the entire block returns a single row

`1×1 DataFrame
│ Row │ m     │
│ 1   │ 22    │`

Is this expected? the workaround would be using 'by' instead of 'combine'

**Comment by pdeffebach** [comment]
Thanks for the issue report!

This is indeed expected. By default `DataFrames.transform` "ungroups" he data after the transformation. Fixing https://github.com/JuliaData/DataFramesMeta.jl/issues/179 to allow keyword arguments is the solution. Eventually it would be nice to do 

```
@transform(m = sum(:b); ungroup = false)
```

which would allow grouping to be preserved in the pipe. 

But this has no been added yet, unfortunately.

**Comment by dbuffoni** [comment]
Great, thank you for your explanation
