### ISSUE TITLE
@transform! does not exist?

### ISSUE THREAD

**Issue by dmetivie** [JuliaData/DataFramesMeta.jl#218]
I have DataFramesMeta v0.6.0 and I cannot use the macro `@transform!` (I get: `ERROR: LoadError: UndefVarError: @transform! not defined`). Is it a problem with my version? The macro `@transform` works well.

**Comment by pdeffebach** [comment]
Sorry! This is my bad. 

I just merged the PR for `@transform!` two days ago (#216). This PR included changes to the readme, which always shows the state of the `master` branch. So the readme contains things which do not exist. 

This was a mistake on my part. I should have not merged changes to the readme until we actually make a new release. 

To use `@select!` and `@transform!` you can add the `master` branch.

**Comment by pdeffebach** [comment]
Fixed via #219
