### ISSUE TITLE
Efficient `map` similar to `@eachrow`

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFramesMeta.jl#222]
Would be nice to do 

```
df.x = @maprows df begin 
    :z + :y 
end
```

**Comment by nalimilan** [comment]
Probably worth coordinating with DataFrames, where this could simply be `map` if we take the logic that `DataFrame` is a collection of rows.

**Comment by pdeffebach** [comment]
yes. though I think this, along with `@with` and a syntax to create anonymous functions, like 

```
@anon :x + :y 
```

becoming 

```
(x, y) -> x + y
```

are DataFrames agnostic and could maybe live somewhere else.

**Comment by bkamins** [comment]
I think `map` in DataFrames.jl will have a limited functionality when/if we add it, to keep it consistent with `map` in Base.

**Comment by nalimilan** [comment]
`filter` already accepts the `cols => fun` syntax though.

**Comment by pdeffebach** [comment]
Keeping this open, but for future readers `@with df @byrow begin ... end` does this perfectly well.

**Comment by pdeffebach** [comment]
Happy with `@with df @byrow ... end`
