### ISSUE TITLE
Document the use of `nrow` in `@combine`

### ISSUE THREAD

**Issue by metanoid** [JuliaData/DataFramesMeta.jl#226]
Within the function `DataFrames.combine` , I can get the number of rows in each group of a GroupedDataFrame using `nrow`.
I tried to get this working using `DataFramesMeta.@combine` instead, and I could not get it to work.

I would sincerely appreciate it if the documentation for `DataFramesMeta` could include an example of how to do this (i.e. pass a function that acts on the group as a whole, rather than the columns).

**Comment by pdeffebach** [comment]
Sorry for never responding to this!

`DataFramesMeta` does not (yet) have the ability to act on a `df` as a whole. Maybe this will be added in the future. best to just use `length(:x)` to get the number of rows in the subdataframe. 

You can always use `DataFrames.combine` which is exceedingly flexible.

**Comment by pdeffebach** [comment]
Closed in favor of #229
