### ISSUE TITLE
Update version and release after DataFrames.jl 1.0 release

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFramesMeta.jl#237]
@pdeffebach - would you be available to do it? (probably next week)
Thank you!

**Comment by pdeffebach** [comment]
Yes, but it won't be 1.0. It also might not include `@subset`.

**Comment by bkamins** [comment]
This is not a problem. I do not want DataFramesMeta.jl hold upgrade of DataFrames.jl to 1.0.
