### ISSUE TITLE
Allow Reexport 1.0

### ISSUE THREAD

**Issue by raphaelsaavedra** [JuliaData/DataFramesMeta.jl#240]
I can see the master already allows Reexport 1+, but a new release has not been tagged yet. Can a release be tagged, so that this package can be used together with others that lower bound Reexport to 1? (e.g. TimeSeries.jl)

Somewhat related to #237 but more pressing since Reexport 1 is already a thing and some packages require it.

**Comment by bkamins** [comment]
We need to do #237 this week, so both are pressing.

**Comment by bkamins** [comment]
@pdeffebach - what do you think?

**Comment by raphaelsaavedra** [comment]
I haven't opened a PR since there have been changes to the master that haven’t been tagged yet, I’m not sure if it should be breaking or not. I'm happy to go ahead and open one, then it's just a matter of tagging, unless there's something blocking it. Then once DataFrames 1 is in, another release can be made?
