### ISSUE TITLE
re-factor code

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFramesMeta.jl#242]
Now that the argument-handling code is so long, it's kind of hard to work with the big `DataFramesMeta.jl` file. 

Is re-factoring into separate files always discouraged? Or is there a way to do it that preserves line-by-line commit histories. 

cc @nalimilan

**Comment by bkamins** [comment]
This is a good idea. I propose you to just split the code into files but without changing anything (then I can easily check that all is OK). And such a PR should contain only "code movement"

**Comment by pdeffebach** [comment]
done in #243

**Comment by bkamins** [comment]
OK to close?
