### ISSUE TITLE
Smarter `@eachrow`

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFramesMeta.jl#249]
As noted in #248, we currently *always* make a full copy of `df` in every `@eachrow`. Users perform the code 

```
s = let x = 0
    @eachrow df begin 
        x += 1
    end
    x
end
```

and expect fast code, when in actuality we are creating a whole new data frame and there will be tons of allocations. 

I'm not sure there's a lot we can do. It makes me wonder if we should make the `!` as the default for everything so users always get the fastest code.

**Comment by bkamins** [comment]
I assume `@eachrow` can mutate the copy of `df`. Right?

In this case I think it is OK that it makes a copy. However, I think it would be good to clearly highlight in the documentation in what cases what solution should be used.

**Comment by pdeffebach** [comment]
Yes. I will emphasize the copying aspect and discuss performance in docstrings in #248

**Comment by nalimilan** [comment]
Yeah the behavior is potentially confusing but it makes sense in general. The only case when it's weird is when you don't mutate columns but only accumulate into a global variable.
