### ISSUE TITLE
@subset: UndefVarError: subset not defined

### ISSUE THREAD

**Issue by permanentrance** [JuliaData/DataFramesMeta.jl#273]
I'm trying to use `@subset` and I'm getting this error:
![image](https://user-images.githubusercontent.com/69864603/127361482-60d3c266-c33e-41a6-a16e-ccd2513e5e67.png)

I'm running Julia v1.6.0 and DataFramesMeta v0.8.0.

The example I'm running is this one:
`d = DataFrame(a = [1, 2, missing], b = ["x", "y", missing]); @subset(d, :a .== 1)`

Note: I ran `using DataFrames; using DataFramesMeta` before this.

**Comment by bkamins** [comment]
What version of DataFrames.jl are you on?

**Comment by bkamins** [comment]
@pdeffebach - the compat part for DataFrames.jl should be updated. Now 0.22 is allowed - and clearly @permanentrance uses this version not 1.x. version.

**Comment by permanentrance** [comment]
I'm on `DataFrames.jl` v0.22.7, I'll have to update julia before moving on, thx @bkamins

**Comment by permanentrance** [comment]
The issue is solve with the following versions:
- Julia v1.6.2
- DataFrames v1.2.1
- DataFramesMeta v0.8.0

**Comment by pdeffebach** [comment]
Apologies for this. I thought I had updated the `compat` to `1.0`. I will do that.

**Comment by pdeffebach** [comment]
Can you post the output of `import Pkg; Pkg.status()`?

**Comment by Danilo-Carajiliascov** [comment]
> Can you post the output of `import Pkg; Pkg.status()`?

HI, pdeffebach.

I finaly solve the problem deleting the file: **~.julia\environments\v1.6\Project.toml** and install all the packages again.

While doing that I noticed some packages was downgraded after installation of some others packages.

It would be nice if **Pkd.update()** was smarter and update all the dependences.
