### ISSUE TITLE
Make docs work on master

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFramesMeta.jl#295]
Docs passed when working on #294, which is why I merged it. But now they fail again on master. 

Need to figure out why this is happening.

**Comment by bkamins** [comment]
it seems they pass on `master` - can you double check (you probably know best where to check 😄)

**Comment by pdeffebach** [comment]
I mean there is still a red X on the most recent commit to master

**Comment by bkamins** [comment]
Ah - yes. I looked in the wrong place. It is broken
