### ISSUE TITLE
How to pass NamedTuple into ByRow function

### ISSUE THREAD

**Issue by wolthom** [JuliaData/DataFramesMeta.jl#309]
I'm currently trying out DataFramesMeta (great work so far!) and experimented a bit with more complex column selection scenarios.
However, I couldn't figure out how to achieve something like the below:
```julia
using DataFrames, DataFramesMeta, VegaDatasets
df = DataFrame(dataset("iris"))
# The transformation below
transform(df, AsTable(Not(:species)) => ByRow(sum) => :s)
```

Is it currently possible to achieve something similar with the macro DSL?

**Comment by bkamins** [comment]
It will be soon https://github.com/JuliaData/DataFramesMeta.jl/pull/307

**Comment by pdeffebach** [comment]
This has been added in #307 and is now released.
