### ISSUE TITLE
Short-circuiting AND for @subset

### ISSUE THREAD

**Issue by kescobo** [JuliaData/DataFramesMeta.jl#310]
Currently, each conditional seems to be evaluated for `@subset`, it would be nice (and possibly more efficient?) to use short-circuiting evaluation

```
julia> df = DataFrame(a = ["xy", "yz", missing, "za"], b=rand(4));

julia> @rsubset(df, !ismissing(:a), !startswith(:a, "x"))
ERROR: MethodError: no method matching startswith(::Missing, ::St
ring)
```

As @bkamins said on slack, one can currently get this behavior using `&&` explicitly:

```
julia> @rsubset(df, !ismissing(:a) && !startswith(:a, "x"))
2×2 DataFrame
 Row │ a        b
     │ String?  Float64
─────┼───────────────────
   1 │ yz       0.701172
   2 │ za       0.757161
```

**Comment by pdeffebach** [comment]
The solution here is to use `@passmissing`. Hopefully in the near-future, `@passmissing` will also be allowed for column-wise operations. Closing this.

**Comment by kescobo** [comment]
The point here was meant to be more broad than just missing operations though. There are lots of `and` conditionals that I use frequently, we could change this to

**Comment by pdeffebach** [comment]
Ah. Thanks for the clarification. 

Regardless, I don't think this is particularly actionable. `@subset` is a thin wrapper around `DataFrames.subset` and I don't think the benefits are large enough to merit what a large re-factor this would be.

**Comment by kescobo** [comment]
Makes sense, no sweat! I opened an issue on DataFrames directly, though I'm guessing it won't make sense there either since you can get the short-circuiting behavior if you really need it, and it's only a modest speed-up at least in my testing
