### ISSUE TITLE
The latest version is not installed

### ISSUE THREAD

**Issue by bojusemo** [JuliaData/DataFramesMeta.jl#329]
The latest version that is installed is DataFramesMeta v0.7.1, and it doesn't update to the latest version (v0.11) when you Pkg.add("DataFramesMeta") or Pkg.update(),. It causes that the error "LoadError: UndefVarError: @rsubset not defined" appears when you try to use @rsubset.

**Comment by bkamins** [comment]
What happens if you do `] add DataFramesMeta@0.11`? See also https://bkamins.github.io/julialang/2020/05/11/package-version-restrictions.html for more context.

**Comment by bojusemo** [comment]
Hi @bkamins ,
Thanks for your reply.
`] add DataFramesMeta@0.11` doesn't solve the problem. This is the error message:

```
(@v1.7) pkg>  add DataFramesMeta@0.11
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package DataFrames [a93c6f00]:
 DataFrames [a93c6f00] log:
 ├─possible versions are: 0.11.7-1.3.4 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.11.7-1.3.4
 ├─restricted by compatibility requirements with DataFramesMeta [1313f7d8] to versions: 1.0.0-1.3.4
 │ └─DataFramesMeta [1313f7d8] log:
 │   ├─possible versions are: 0.4.0-0.11.0 or uninstalled
 │   └─restricted to versions 0.11 by an explicit requirement, leaving only versions 0.11.0
 └─restricted by compatibility requirements with PooledArrays [2dfb63ee] to versions: 0.11.7-0.22.7 or uninstalled — no versions left
   └─PooledArrays [2dfb63ee] log:
     ├─possible versions are: 0.3.0-1.4.2 or uninstalled
     └─restricted by compatibility requirements with JuliaDB [a93385a2] to versions: 0.4.1-0.5.3
       └─JuliaDB [a93385a2] log:
         ├─possible versions are: 0.9.0-0.13.1 or uninstalled
         └─restricted to versions * by an explicit requirement, leaving only versions 0.9.0-0.13.1
```

I also tried `] add DataFramesMeta@0.11.7-1.3.4` and `] add DataFramesMeta@0.11.7`, but they did't work.

**Comment by bkamins** [comment]
Please do not use Atom. It has not been maintained for some quite time now and is known to have a problem with proper package versions.

The recommended IDE is VS Code with Julia extension https://www.julia-vscode.org/.
