### ISSUE TITLE
operators do not work inside function call inside macros

### ISSUE THREAD

**Issue by adienes** [JuliaData/DataFramesMeta.jl#352]
Saw this on Discourse, just wanted to make sure it got flagged in an issue.

```
julia> df = DataFrame((; a=[1,2,3], b=[4,5,6], x=[1,1,2]));

julia> group = groupby(df, [:x]);

julia> @combine(group, :z = sum(:a .* :b)) #BREAKS
ERROR: UndefVarError: `.*` not defined

julia> @combine(group, :z = (:a .* :b) |> sum) #works
julia> @combine(group, :z = sum(max.(:a, :b))) #also works
```

**Comment by bkamins** [comment]
This is fixed on master. It will be included in the next release. For the mean time add `#master` instead of latest release to your project.

**Comment by adienes** [comment]
awesome, sorry for the noise

**Comment by bkamins** [comment]
No problem - it is important to get some feedback, so that @pdeffebach pushes for the release 😄.
