### ISSUE TITLE
`ByRow` not defined when importing DataFramesMeta

### ISSUE THREAD

**Issue by jwright11** [JuliaData/DataFramesMeta.jl#365]
Hello, I was trying to do this:
```
import DataFrames
import DataFramesMeta
df = DataFrames.DataFrame(a = 1:10)
DataFramesMeta.@rsubset!(df, :a < 6)
```
But I get: 
```
ERROR: UndefVarError: `ByRow` not defined
```
I'm using Julia v1.9.3 with DataFrames v1.6.1 and DataFramesMeta v0.14.0.
Am I going about this wrong?

**Comment by pdeffebach** [comment]
Thank you! This is most likely a bug with my escaping. I will try to fix it asap.
