### ISSUE TITLE
docs question

### ISSUE THREAD

**Issue by spaette** [JuliaData/DataFramesMeta.jl#369]
Does the first paragraph need to be rewritten?

I intend to submit a pull request pending clarification.

````
$ ed -s DataFramesMeta.jl/src/macros.jl <<<'2798, 2820p'
### Details

Both the left- and right-hand side of an expression specifying a column name assignment
can be either a `Symbol` or an `AbstractString` (which may contain apces) escaped with `
$DOLLAR`. For example `:new = ...`, and `$(DOLLAR)"new" = ...` are both valid ways
of assigning a new column name.

This idea can be extended to pass arbitrary right-hand side expressions. For example,
the following are equivalent:

```
@rename(df, :new = :old1)
```

and

```
@rename(df, :new = $("old_col" * "1"))
```

The right-hand side can additionally be an `Integer`, escaped with $(DOLLAR), to indicate
column position. For example, to rename the 4th column in a data frame to a new name, write
`@rename df :newname = $(DOLLAR)`.
$ 
````

**Comment by spaette** [comment]
Perhaps I misunderstand however the author's intent in that paragraph.

> obvious typo

Were  `apces` the typo would the fix possibly be either of `ellipses` or `an ellipsis`?

**Comment by spaette** [comment]
Aside from the correction of that paragraph the repo had a second typo.

```
$ grep -nr dont DataFramesMeta.jl
DataFramesMeta.jl/test/parsing.jl:125:    # Some errors when we dont have keyword arguments, since
$ 
```

**Comment by spaette** [comment]
> Were  `apces` the typo would the fix possibly be either of `ellipses` or `an ellipsis`?

@bkamins

Would you chip in on this ticket?

Looking at the string `apces` it occured to me the author's intent may have been `spaces`.

Otherwise the singular `an ellipsis` would seem more fitting than the plural  `ellipses`.

**Comment by pdeffebach** [comment]
No need to ping Bogumil. You are entirely correct. Please open a PR with those changes.

**Comment by spaette** [comment]
> entirely correct

Evidently not in regards to my interpretation of what you wrote in your comments.

Pull has been fixed with a soft reset performed.
