### ISSUE TITLE
Error in the @by example in the documentation

### ISSUE THREAD

**Issue by sbacelar** [JuliaData/DataFramesMeta.jl#396]
The example of `@by` in the documentation gives an error: `ERROR: ArgumentError: column :x in returned data frame is not equal to grouping key :x
`
Maybe it was better ` :y_sum = sum(:y)`
```
using DataFrames
using DataFramesMeta

df = DataFrame(x = [1, 1, 2, 2], y = [1, 2, 101, 102]);
@by df :x begin
           :x = sum(:y)
           end
```

**Comment by pdeffebach** [comment]
Good catch!
