### ISSUE TITLE
Rename based_on()?

### ISSUE THREAD

**Issue by nalimilan** [JuliaData/DataFramesMeta.jl#52]
As noted in https://github.com/JuliaStats/DataFramesMeta.jl/issues/48, `based_on` might not be the best name for this operation. It's hard to distinguish from `groupby` (and doesn't follow the same naming convention with regard to the underscore).

`summarize`/`summarise` (like dplyr) might be more explicit. But it's a bit surprising that this operation also allows returning as many rows as in the original data, which is completely different from summarizing.

I wonder whether it couldn't be merged with `select`, as in SQL. AFAICT `select` doesn't work on `GroupedDataFrame` currently, so there would be no conflict.

**Comment by tshort** [comment]
I dislike the name `based_on`, so I'm good with a change. `select` would probably work.

**Comment by nalimilan** [comment]
It looks like that use of `select` would be more or less consistent with LINQ: https://msdn.microsoft.com/en-us/library/bb386922%28v=vs.110%29.aspx

(Another possibility would be `combine`, but I'm not sure it's used anywhere else.)

**Comment by ararslan** [comment]
+1 for changing the name. `based_on` isn't very descriptive and IMO is actively confusing given what it actually does.

**Comment by sswatson** [comment]
Is there still support for this change? Seems like it would be easy to implement if folks still want to do it.

**Comment by nalimilan** [comment]
Yes, I think we should merge `based_on` with `select` and `transform`. There's no reason to have a separate function for summarizing: whether the result contains one row per group or multiple rows per group can be determined dynamically based on whether the function returns a row or a data frame. DataFrames does this with `combine` on current master, and with https://github.com/JuliaData/DataFrames.jl/pull/1601 DataFramesMeta could just call `combine`, passing it the column names and an anonymous function. You're welcome to experiment with that.

**Comment by sswatson** [comment]
Thanks for the update; I didn't realize just how current this issue is over on the DataFrames front. I'll revisit the issue a bit later, and if it seems some effort would be appreciated to make this happen on DataFramesMeta, I'll give it a try.

**Comment by nalimilan** [comment]
@pdeffebach Is there any reason to keep `@based_on` now that you implemented `@transform`?

**Comment by pdeffebach** [comment]
yes, we will definitely rename `@based_on` to `@combine`.

**Comment by pdeffebach** [comment]
Closed via #167
