### ISSUE TITLE
Support `_DF` (or something) for full DataFrame access

### ISSUE THREAD

**Issue by tshort** [JuliaData/DataFramesMeta.jl#86]
We used to have this "hidden" feature where you could use `_DF` to access the whole DataFrame (or SubDataFrame in a group operation). It is occasionally nice. I think it got coded out in https://github.com/JuliaStats/DataFramesMeta.jl/pull/73.

**Comment by piever** [comment]
I've been playing with this in JuliaDBMeta and I think the nicest is to use `_` (just like what Query does, as well as the proposed [new anonymous function syntax](https://github.com/JuliaLang/julia/pull/24990)). It could actually be a non-hidden feature and make the `_I_` syntax less necessary as one can just do `_[expr]` which is even shorter.

**Comment by tshort** [comment]
Interesting on the JuliaDBMeta approach. I'm curious if you run into stumbling blocks with `_`. BTW, great to see JuliaDBMeta. I'm looking forward to using JuliaDB more, and having JuliaDBMeta will make it nicer!

**Comment by piever** [comment]
`_` works pretty well as it is warned against in Julia's normal syntax so it doesn't really appear in normal code.
For now I'm making `_` be the whole `DataFrame` for "column based macros" and the whole row as a NamedTuple for "row based macros". Ideally it should also be the appropriate subdataframe when working with grouping data but I haven't figured out the grouping part yet (JuliaDB grouping API is already quite powerful, it's not too obvious how to improve on it...).

**Comment by pdeffebach** [comment]
Closed in favor of #229
