### ISSUE TITLE
Better interplay with Lazy

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFramesMeta.jl#96]
DataFramesMeta and Lazy work very well together, and personally I like the `@>` syntax the best out of all the chaining. 

However the two packages export conflicting names, which is frustrating. 

```
julia> using Lazy, DataFramesMeta, DataFrames

julia> df = DataFrame(rand(10,10));

julia> @with df begin
       y = :x1
       end
WARNING: both DataFramesMeta and Lazy export "@with"; uses of it in module Main must be qualified
ERROR: UndefVarError: @with not defined
```
and

```
 groupby(df, :x1)
WARNING: both DataFrames and Lazy export "groupby"; uses of it in module Main must be qualified
```

What can be done to make sure these conflicts don't pop up?

**Comment by tshort** [comment]
To avoid the conflicts, just pull in the parts of Lazy you want:

```julia
using DataFramesMeta, DataFrames
import Lazy: @>, @as
```
At the package level, an option to consider is pulling in a version of `@>` into DataFramesMeta.

**Comment by pdeffebach** [comment]
I was thinking of the users who are used to scripting and give up one they have to think of module scoping. `import Lazy: @>, @as` is definitely easy. 

Renaming `@with` seems like overkill. 

Maybe we should just add to the `docs` in the `@>` example just importing `@>` from Lazy.

**Comment by tshort** [comment]
+1 to that.

**Comment by nalimilan** [comment]
It could make sense to have DataFramesMeta reexport `@>` from Lazy.

**Comment by pdeffebach** [comment]
This just means adding `@reexport using Lazy: @>` to the top of the file right? Maybe export `@as`, too?

**Comment by pdeffebach** [comment]
Now that `@linq` has been revamped so you don't need the `@`. How much work would it be to have the following? It's hard for me to tell, but it might not be trivial since `@linq` inspects the expressions for `|>` manually.  

```
df2 = @linq df begin 
    transform(a = :b)
end
```
